try {
    throw new Error('My Error')
} catch (err) {
    console.log(err);
}